### ISSUE TITLE
How should we translate these contents?

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio-school#10]
The [user manual](https://github.com/loomio/user-manual/) is organized in locales subfolders, which allows translating it in GitHub. Loomio School, however, is not organized in the same way.

Is there a plan for Loomio School translations? Should we move the current content to an en folder and create other locales folders for translation? How can we manage redirections from the current URIs to the /en/ new ones?

**Comment by robguthrie** [comment]
Actually, we'd really like to merge the user-manual with loomio-school, so it becomes a section within it. It's quite confusing that we have two help/support sites.

Redirections are pretty easy to handle we do it in one place, just need to make it generalised.

Yes, we should move it to an en folder, if you have the energy that would be amazing.

**Comment by robguthrie** [comment]
to be clear, Loomio-school would be the main help site, and the user-manual would be a section within it.

**Comment by juliencarnot** [comment]
Ok, that makes sense. I'll focus on updating the user-manual for a start, and will try to PR this if I find enough time.

**Comment by juliencarnot** [comment]
closing this in favour of #13
